### ISSUE TITLE
Add more descriptive README with information "what does this tool for?"

### ISSUE THREAD

**Issue by narqo** [bem/bemhint#17]
From the current README it quite to impossible to understand, what kind of linting this tool does. 

I suggest you to add some light description about the possibilities of the tool. So the enduser can understand if he need it for his project or not.

**Comment by eGavr** [comment]
I am working on this task right [now](https://github.com/eGavr/bemhint/pull/16).

And I'll describe the rule which bemhint uses.

**Comment by zxqfox** [comment]
:+1: Great idea, if I see it right.

Recommendations:
- make rules as simple as possible;
- split them to blocks with readme, specs, etc. (you can see what happend with jscs: docs in jsdoc and tests for rules manually formatted to the same structure as in `./lib`);
- don't use excludeFiles, use `.bemhintignore` via https://www.npmjs.com/package/ignore or something else.

**Comment by eGavr** [comment]
> split them to blocks with readme, specs, etc. (you can see what happend with jscs: docs in jsdoc and tests for rules manually formatted to the same structure as in ./lib);

there is only one rule now

> don't use excludeFiles, use .bemhintignore via https://www.npmjs.com/package/ignore or something else.

No, I do not want to use two config files.

**Comment by tadatuta** [comment]
the very first thing to mention in readme is that it doesn't support `bem-core` now.
