### ISSUE TITLE
Self dependence

### ISSUE THREAD

**Issue by Yeti-or** [bem/bemhint#25]
Modificator must not depend from block.:
```
common.blocks/i-bem/__dom/_init:
actual:   'No deps file i-bem__dom_init_auto.deps.js'
expected: { block: 'i-bem' }
```

**Comment by eGavr** [comment]
Думал,  что в таких вариантах надо прописывать зависимость.

Хорошо, поправлю.

**Comment by eGavr** [comment]
А если бы на этом уровне мы заюзали BEM.internal, то в зависимости его надо было бы прописать?
