### ISSUE TITLE
Заполнить readme.md

### ISSUE THREAD

**Issue by bratva** [bem/bemhint#42]
Привет. 
Заполните пожалуйста Readme.md информацией о том - что эта за библиотека и как ей пользоваться. Говорят, она умеет построить deps зависимости - так ли это?

**Comment by eGavr** [comment]
@bratva Это не библиотека, а тулза.
Нет, строить депсы не умеет, разрабатывается в качастве линтера для депсов.
тулза в состоянии `Work In Progress`

**Comment by eGavr** [comment]
А кто тебя так дизинформировал ? :)

**Comment by bratva** [comment]
Арикон =)
>  Чтобы использовать технологию deps, зависимости на проекте должны быть описаны максимально полно. В этом может помочь утилита bemhint.

**Comment by eGavr** [comment]
Ты немного, я думаю, не правильно интерпретировал)

**Comment by bratva** [comment]
Ооок =) Будь у вас внятный readme.md, вопросов бы не возникло.

**Comment by eGavr** [comment]
Согласен,  мой косяк :(
