### ISSUE TITLE
.bemhint –> .bemhint.js || .bem/hint.js

### ISSUE THREAD

**Issue by eGavr** [bem/bemhint#45]

**Comment by zxqfox** [comment]
`.config/bem/hint.js`?

`$XDG_CONFIG_HOME = $HOME/.config` http://standards.freedesktop.org/basedir-spec/latest/ar01s03.html

**Comment by voischev** [comment]
Про это никто не знает. ;) значит стандарт не работает

**Comment by zxqfox** [comment]
@voischev Слущай, зачем па сибе судишь, да?

![](https://leto30d.storage.yandex.net/rdisk/f385e37bfc762f86a46e766a5d9b882629dab55391b2a67e335f849344f64bd5/inf/mMyML61I0CGua0y9HTMeEKURbJ2Veleb_HtS-J6eN4OGI9JpImjPvg5CFPB7BL_3C3YMRFCRzwLfUT5queiSXA==?uid=0&filename=Monosnap_2015-12-13_00-39-31.png&disposition=inline&hash=&limit=0&content_type=image%2Fpng&tknv=v2&rtoken=469a739660ed19fe41c0ba912fc85b5f&force_default=no&ycrid=na-50f3f9e2d46d1702760b518f5b440973-downloader10g)

https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/git-config.1.html
https://github.com/search?utf8=✓&q=xdg
http://stackoverflow.com/questions/3373948/equivalents-of-xdg-config-home-and-xdg-data-home-on-mac-os-x

**Comment by voischev** [comment]
Пф. А теперь сделай ls -a ~/ и ls -a ~/.config/ ;) где больше конфигов?

**Comment by zxqfox** [comment]
@voischev Ну такое ;-)
```js
$ ls -la ~/.config | wc -l
      10
```

**Comment by voischev** [comment]
Не "такое", а правда жизни ;)

**Comment by zxqfox** [comment]
А почему не пользоваться bem-config в этом месте?

**Comment by eGavr** [comment]
Начиная с версии `0.5.x` по умолчанию конфиг ожидается в файле `.bemhint.js`.
